import 'package:get/get.dart';
import 'package:uuid/uuid.dart';

import '../../../data/models/app_notification_model.dart';

/// A lightweight in-memory notification center for transaction/security
/// alerts generated by real app events — separate from FCM's remote push,
/// which handles server-originated notifications. Together they cover both
/// "the app told me something happened" and "a server told me something
/// happened," matching how real banking apps typically layer these.
class NotificationCenterController extends GetxController {
  final RxList<AppNotification> notifications = <AppNotification>[].obs;

  int get unreadCount => notifications.where((n) => !n.isRead).length;

  void add({required AppNotificationType type, required String title, required String body}) {
    notifications.insert(
      0,
      AppNotification(
        id: const Uuid().v4(),
        type: type,
        title: title,
        body: body,
        timestamp: DateTime.now(),
      ),
    );
  }

  void markAsRead(String id) {
    final index = notifications.indexWhere((n) => n.id == id);
    if (index >= 0) {
      notifications[index] = notifications[index].copyWith(isRead: true);
    }
  }

  void markAllAsRead() {
    notifications.assignAll(notifications.map((n) => n.copyWith(isRead: true)).toList());
  }
}